[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "interpy_bg"
version = "0.1.0"
description = "5D Interpolation library for FastAPI backend"
readme = "README.md"
authors = [
    { name = "Baron Gracias", email = "bg492@cam.ac.uk" }
]
requires-python = ">=3.13"
dependencies = []

[project.urls]
Homepage = "https://github.com/yourusername/interpy_bg"
